#+OPTIONS: toc:2 author:nil ^:nil date:nil

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt, a4paper]
#+LATEX_HEADER: \usepackage{fullpage}
#+LATEX_HEADER: \usepackage{authblk}
#+LATEX_HEADER: \usepackage{setspace} % for adjust TOC line spacing
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\parskip}{1em}
#+LATEX_HEADER: \setlength{\affilsep}{0.5em}

#+TITLE: Telomere project: outline of main results
#+LATEX_HEADER: \author{Kyle M. Douglass}
#+LATEX_HEADER: \affil{Institute of Physics of Biological Systems, EPFL, Lausanne, Switzerland}

#+BEGIN_ABSTRACT
Presented at the top level of the outline are the main assertions and
conclusions concerning the telomere project and what will be discussed
in the manuscript. The main pieces of evidence that support these
conclusions are discussed, as well as the weak points.
#+END_ABSTRACT

#+LATEX: % adjust TOC line spacing
#+LATEX: \addtocontents{toc}{\protect\setstretch{0.1}}

* Telomere sizes can be assessed using STORM microscopy

** Reasoning: The radius of gyration is a good measure of size
   The radius of gyration of a point cloud that represents one
   telomere reflects the radius of gyration ($R_g$) of the underlying
   telomere. This is largely an assertion based on what we know of how
   STORM microscopy works and not necessarily a conclusion that can be
   strictly proven.

** Support: Our numbers are similar to the Zhuang lab paper
   The Zhuang lab measured diameters of the localization
   distribution. This number is roughly the same as our mean radius of
   gyration. While not direct evidence of this point, we can claim
   consistency with prior results. Also, the genomic lengths of their
   mouse embryonic fibroblasts are similar to ours.

** Support: Size correlates to the genomic distance
   Hela S telomeres have shorter genomic lengths than Hela L. They
   also have smaller measured sizes.

** Weak point: the telomeres are not fully labeled
   The average number of localizations found in a telomere is between
   100 and 200. However, given a label size of 18 base pairs and an
   average genomic size of 10 kb for Hela S and 25 kb for Hela L, we
   know that this corresponds to a labeling efficiency of
   $\frac{100}{10000 / 18} = 0.18$, or about 20\%. This means
   undersampling might bias the results.

*** TODO variation in $R_g$ is small when subsampling
    We can remove points from telomere clusters and show the
    dependence of $R_g$ on the number of points removed. This would
    tell us how strongly the value depends on any given set of points.

*** TODO simulations of real $R_g$ vs. subsampled $R_g$
    We can simulate a large number of polymers and simulate what
    happens if we label only a fraction of their points.

** Weak point: the telomere size depends on number of frames
   We see a slight increase (~5 nm, or about 5\% to 6\% of the mean)
   in average size when the we image with 30,000 frames. This could be
   due to stage drift. It's supposedly corrected for using the
   autocorrelation method, but how precise is this method?

** Weak point: cluster sizes depend on staining
   Immunofluorescence staining of TRF1 showed a smaller telomere size
   than DNA FISH staining. \textbf{But}, these measurements label
   different parts and may have different linker sizes between the
   label and the fluorescent marker. Is this a fair comparison?

** Weak point: small telomeres will appear disproportionately large
   Smaller telomere sizes will \textit{appear} disproportionately
   larger than their real size than larger ones due to the
   localization uncertainty.

*** Counter argument : this can be taken into account
    If we know the localization precision, we can correct for this. In
    fact, this effect is already taken into account in our estimation
    of the model parameters for compaction and persistence length.
    
** Weak point: DNA FISH ruins the local DNA structure
   I'm not sure if we can really debate this point or whether its
   known to what extent higher order structure is destroyed when
   performing FISH.

*** Counter argument: IF TRF1 measurements show similar sizes
    The immunofluorescence labeling can actually be a strong point in
    this case. Because we only measure a small change in size from IF,
    we can claim that the compaction of is roughly preserved when FISH
    is performed.

    The actual difference in Hela L TRF1 IF and Hela L WT FISH is
    about 20 nm in the mean radius of gyration.

    What constitutes a small change in size here?

-----
* Hela L telomeres are more compact than Hela S telomeres
** Support: The density increases with volume when comparing Hela types
   We can easily make this statement by taking the wild type mean
   radius of gyration for both cell types as a characteristic radius
   of a telomere. The mean gyration radii for Hela L and Hela S are
   $R_g \approx 100 \, nm$ and $R_g \approx 77 \, nm$
   respectively. The average genomic lengths are $N = 25 \, kb$ and $N
   = 10 \, kb$, respectively.

   The ratio of the average telomere volume is therefore

   \begin{equation*}
\frac{R_g^3 \left( L \right)}{R_g^3 \left( S \right)} \approx 2.2
   \end{equation*}

   However, the ratio of the genomic lengths is

   \begin{equation*}
\frac{N \left( L \right)}{N \left( S \right)} = 2.5
   \end{equation*}

    Because the ratio of genomic lengths is larger than the volume, this
    suggests that there is more Hela L telomeric DNA per volume than Hela
    S DNA.

    /textbf{Note that some of the biochemical tests have placed the
    average of the Hela L genomic length at an even larger value, which
    would mean there's even more compaction.}

    Also, the ratio of the volumes using the median radius of gyration
    is 2.1148, similar to the ratio of means.

** Support: There are more heterochromatic marks on Hela L
   There are more H3K9me3 marks on Hela L cells, a mark that
   correlates to heterochromatin.

** Support: Polymer modeling places larger compaction limit on Hela L
   The results of the polymer modeling places the upper limit on the
   packing ratio for Hela L at about 50 bp/nm, where as the upper
   limit is about 40 bp/nm in Hela S.

   This is not proof that Hela L is more compact, but supports the
   other conclusions listed here.

** Weak point: Small changes to compaction
   I've made estimates that we need a precision in the mean values for
   the radius of gyration that's between plus or minus 5 and 15 nm to
   make accurate statements about compaction of one cell type
   vs. another. The precision is probably closer to 15 nm since it is
   derived from the scaling law for a Gaussian chain ($N \sim R_g^2$)
   and the 5 nm value is derived from the scaling law for constant
   density ($N \sim R_g^3$). Other work suggests the scaling at this
   length scale is closer to the Gaussian chain (Bancaud, 2012).

   We're probably right at the limits of the achievable precision to
   assess compaction differences.

-----
* There is no 30 nm-fiber like structure in Hela telomeres
** Reasoning: Best-fit packing ratios are well below 30 nm fiber ratio
   The highest upper limit on the packing ratios that describe our
   data is about 50 bp/nm, but the 30 nm fiber is twice this at 100
   bp/nm.
** Support: parameter estimations undoubtedly say this
   The parameter plots place upper bounds on the polymer parameters
   that best describe the telomeres, and these upper bounds lie
   nowhere near the 30 nm packing density of 100 bp/nm. I believe this
   is both a strong and unambiguous conclusion.

   The only weak points concern the application of the worm-like chain
   model to the data.

** Weak point: t-loops
   T-loops will make part of the polymer appear as circular, not
   linear. One of the best arguments we have for not including them is
   that t-loops contribute to the higher order structure in a way that
   influences the packing density. Since we assess the packing density
   in our model, we indirectly measure the effect of t-loops.

*** Counter argument: t-loops are highly heterogeneous
    Not all in vitro telomeres in the Zhuang paper have
    t-loops. Furthermore, if they did, the size of the loop relative
    to the entire size of the telomere varied by a very large amount
    (it was almost uniform, see Fig. 2G in the paper).

    Therefore, not accounting for the t-loop probably has less of an
    effect on our results than if every telomere had a t-loop. If
    every telomere had a t-loop, the linear polymer model would be
    much more biased.

*** Counter argument: t-loops are included in the packing density
    We measure the packing density of the linear polymer, in which
    higher order structure abstracted way into the details of the
    polymer fiber itself. t-loops may be one such higher order
    structure.

*** Counter argument: they've only been observed in vitro
    Is this true? Is it really a good argument to suggest they don't
    exist because we've never seen them in vivo?
    
** Weak point: G-quadruplexes
   We don't specifically allow for G-quadruplexies, at least
   directly...

*** Counter argument: These actually cause greater compaction
    Packaging by G-quadruplexes should effectively appear as a larger
    telomeric compaction in our model. Since we account for/measure
    compaction, we are indirectly including them. This also follows
    the same line of reasoning as the t-loops.

-----
* TRF1 and TRF2 knockdowns affect telomere size
** Evidence: Visual comparison of distributions
   We see a consistent difference in $R_g$ distributions for Shelterin
   knockdowns.
** Evidence: Significance tests
   The significance tests that I performed showed differences and a
   typical uncertainty in the mean of about 5 nm.

** Evidence: ChIP shows a correlation
   ChIP measurements show that TRF2 knockdowns should have a large
   amount of heterochromatic marks.
** Weak point: the controls differed from the wild type
   The control means differ from the wild type means, but not by as
   much as the Shelterin knockdowns. We can claim that this puts a
   limit of about 5 nm on what we can tell based on distributions.

** Weak point: day-to-day variation is large
   The day-to-day variation in the means (and medians) is roughly the
   same as the minimum precision I estimated above that was necessary
   to unequivocally assess compaction changes between two cell
   types. Is this enough precision?

-----
