function createfigure(xdata1, ydata1, zdata1, X1, Y1, Z1, S1, C1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, X1, Y1, Z1, S1, C1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c

%  Auto-generated by MATLAB on 23-Dec-2014 09:39:31

% K -> xdata1, EPS -> ydata1,
% reshape(outputData(1).distributions.numClusters, 17, 10) -> zdata1
% X1, Y1, Z1 = 8, 65, 2450

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'all');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1);

% Create xlabel
xlabel('Minimum points per cluster');

% Create ylabel
ylabel('Neighborhood radius, nm');

% Create zlabel
zlabel('Number of identified clusters');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'MarkerFaceColor',[1 1 1],'LineWidth',5);

